name: CI

on:
  push:
    branches: [ kanais7/add_actions ]
  pull_request:
    branches: [ kanais7/add_actions ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
          - iOS
          - Android

    steps:
      - name: Checkout
        run: |
          branch_name=${GITHUB_REF#refs/heads/}

          git init
          git remote add origin https://github.com/kanais7/BoatAttack.git

          git config lfs.fetchinclude '*.dll'

          git fetch --depth=1 origin ${branch_name}
          git lfs fetch origin origin/${branch_name}
          
          git checkout ${branch_name}

      - name: Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-

      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: CompileTester.DefaultTests.CurrentPlatform
