name: CI

on:
  push:
    branches: [ kanais7/add_actions ]
  pull_request:
    branches: [ kanais7/add_actions ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: |
          git init
          git remote add origin https://github.com/kanais7/BoatAttack.git

          git config lfs.fetchinclude '*.dll'

          git fetch --depth=1 origin master
          git lfs fetch origin origin/master
          
          git checkout master

      - name: Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          buildMethod: CompileTester.DefaultTests.StandaloneOSX
